const AUTH_BASE = '/auth'
export const NO_AUTH_LOGIN = AUTH_BASE + '/no-auth-signin'
export const AUTH_LOGIN = AUTH_BASE + '/auth-signin'
export const OTP = AUTH_BASE + '/otp'
export const SIGNUP = AUTH_BASE + '/signup'
export const FORGET_PASSWORD = AUTH_BASE + '/forget-password'
const APP_BASE = '/app'
export const DASHBOARD = APP_BASE + '/dashboard'
export const REQUEST = APP_BASE + '/request'
export const PAYROLL = APP_BASE + '/payroll'
export const ASSETS = APP_BASE + '/assets'
export const PERFORMANCE = APP_BASE + '/performance'
const APP_ADMIN_BASE = '/admin'
export const ADMIN_DASHBOARD = APP_ADMIN_BASE + '/dashboard'
export const CAMPAIGN = APP_ADMIN_BASE + '/campaign'
export const ORGANIZATION = APP_ADMIN_BASE + '/organization'
export const EMPLOYEE = APP_ADMIN_BASE + '/employees'

export const INVENTORY = APP_ADMIN_BASE + '/inventory'
//api
const API_BASE = '/api'
export const API_AUTH_BASE = API_BASE + '/auth'
export const API_ADMIN_BASE = API_BASE + '/admin'
export const API_EMPLOYEE_BASE = API_ADMIN_BASE + '/employee'
export const API_ORGANIZATION_BASE = API_BASE + '/organization'
export const API_CAMPAIGN_BASE = API_BASE + '/campaign'
export const API_ASSETS_BASE = API_BASE + '/assets'
export const API_PERFORMANCE_BASE = API_BASE + '/performance'
export const API_REQUEST_BASE = API_BASE + '/request'
export const API_PAYROLL_BASE = API_BASE + '/payroll'
export const API_INVENTORY_BASE = API_ADMIN_BASE + '/inventory'
export const API_CREATE_INVENTORY = API_INVENTORY_BASE + '/create'
//auth
export const API_AUTH_LOGIN = API_AUTH_BASE + '/login'
export const API_AUTH_SIGNUP = API_AUTH_BASE + '/signup'
export const API_AUTH_FORGET_PASSWORD = API_AUTH_BASE + '/forget-password'
export const API_AUTH_OTP = API_AUTH_BASE + '/otp'
export const API_AUTH_NO_AUTH_LOGIN = API_AUTH_BASE + '/no-auth-login'
//admin
export const API_CREATE_EMPLOYEE = API_EMPLOYEE_BASE + '/create'
export const API_UPDATE_EMPLOYEE = API_EMPLOYEE_BASE + '/update'
export const API_DELETE_EMPLOYEE = API_EMPLOYEE_BASE + '/delete'
export const API_READ_ALL_EMPLOYEE = API_EMPLOYEE_BASE + '/read-all'
//dummt-data
export const API_CREATE_DUMMY_EMPLOYEE =
  '/api' + AUTH_BASE + '/user/create-dummy-user'

export const API_USER_BASE = API_BASE + '/user'
export const API_CREATE_TIME_LOG: string = API_USER_BASE + '/time-log/create'
